name: "SIMPLE IPFS Downloader"

on:
  workflow_dispatch:

jobs:
  download-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 1. Clean & Checkout
        run: |
          # پاک کردن همه چیز برای شروع تازه
          rm -rf .git
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git .
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: 2. Download File with curl
        run: |
          echo "Downloading..."
          curl -L -o mydownloadedfile "https://ipfs.io/ipfs/QmNf1UsmdGaMbpatQ6toXSkzDpizaGmC9zfunCyoz1enD5/penguin/"
          echo "Download finished. File info:"
          ls -la mydownloadedfile
          file mydownloadedfile

      - name: 3. Commit and Push
        run: |
          git add mydownloadedfile -f
          git commit -m "Add downloaded file from IPFS" || echo "Nothing new to commit"
          git push
