name: "Fetch IPFS Folder as CAR File"

on:
  workflow_dispatch:

jobs:
  fetch-ipfs-folder:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download the entire folder as a single CAR file
        run: |
          echo "Downloading the IPFS folder as a CAR file..."
          curl -L -o penguin_folder.car "https://ipfs.io/ipfs/QmNf1UsmdGaMbpatQ6toXSkzDpizaGmC9zfunCyoz1enD5?format=car"
          echo "Download completed. File info:"
          ls -lh penguin_folder.car

      - name: Commit and Push the CAR file to GitHub
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add penguin_folder.car
          git commit -m "Add IPFS folder as a CAR file" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
