name: "Fetch from IPFS and Commit"

on:
  workflow_dispatch:   # یعنی فقط خودت با یک دکمه اجرا کن

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download file from IPFS
        run: |
          # لینک IPFS شما
          IPFS_URL="https://ipfs.io/ipfs/QmNf1UsmdGaMbpatQ6toXSkzDpizaGmC9zfunCyoz1enD5/penguin/"
          curl -L "$IPFS_URL" -o downloaded_file.png
          # اگر فایل ZIP نیست، نام فایل را عوض کن (مثل myfile.pdf)

      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add downloaded_file.zip
          git commit -m "Add file from IPFS" || echo "No changes"
          git push
